export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  UPDATESOFTWAREPROFILE: "/update_profile/software",
  UPDATESTUDENTPROFILE: "/update_profile/student",
  SOFTWAREHOUSE: "/softwarehouse/completeprofile",
  INVESTOR: "/investor/completeprofile",
  SOFTWAREHOUSEHOME: "/softwarehouse/home",
  JOBDETAIL: "/jobDetail/:id",
  STUDENTHOME: "/student/home",
  JOBS:"/jobs",
  PROJECTS:"/projects",
  PROJECTDETAIL:"/projectDetail/:id",
  REVIEWS:"/reviews",
  INVESTORHOME:"/investor/home",
  STUDENTS:"/students",
  STUDENTDETAIL:"/studentDetail/:id",
  INVESTORS:"/investors"
};
